version: '2'
services:
  ui-mongodb:
    image: mongo:4.0.9
    ports:
      - '27017:27017'
    command: mongos --configdb ui-mongodb-config
  ui-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  ui-mongodb-config:
    image: mongo:4.0.9
    container_name: ui-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
