version: '2'
services:
  meeting-app:
    image: meeting
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://meeting-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=meeting
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
  meeting-mongodb:
    extends:
      file: mongodb.yml
      service: meeting-mongodb
