apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meeting-virtualservice
  namespace: office
spec:
  hosts:
    - meeting
  http:
    - route:
        - destination:
            host: meeting
            subset: 'v1'
          weight: 100
      retries:
        attempts: 3
        perTryTimeout: 2s
