apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: leave-virtualservice
  namespace: office
spec:
  hosts:
    - leave
  http:
    - route:
        - destination:
            host: leave
            subset: 'v1'
          weight: 100
      retries:
        attempts: 3
        perTryTimeout: 2s
