apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ui-gateway
  namespace: office
  labels:
    gateway: ui-gateway
    istio: ingressgateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - ui.35.184.190.237.nip.io
    - port:
        number: 80
        name: http2
        protocol: HTTP2
      hosts:
        - ui.35.184.190.237.nip.io
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ui-gw-virtualservice
  namespace: office
  labels:
    service: ui-gw-virtualservice
spec:
  hosts:
    - ui.35.184.190.237.nip.io
  gateways:
    - ui-gateway
  http:
    - match:
        - uri:
            prefix: /services/organization/
      route:
        - destination:
            host: organization
    - match:
        - uri:
            prefix: /services/leave/
      route:
        - destination:
            host: leave
    - match:
        - uri:
            prefix: /services/meeting/
      route:
        - destination:
            host: meeting
    - match:
        - uri:
            prefix: /services/notification/
      route:
        - destination:
            host: notification
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: ui
